#!/usr/bin/env bash
set -e

SRC_DIR="src"
BUILD_DIR="build"
IMG="$BUILD_DIR/main_floppy.img"

mkdir -p "$BUILD_DIR"
nasm "$SRC_DIR/boot.asm" -f bin -o "$BUILD_DIR/bootloader.bin"

qemu-system-i386 -drive file=$BUILD_DIR/bootloader.bin,format=raw,index=0,media=disk

# nasm "src/boot.asm" -f bin -o "build/bootloader.bin"
